from board import Board

def f():
    board = Board("first", "second")
    board.print_board()
    print(board.turn)
    print(board.move("first", (6, 4), (4, 4)))
    board.print_board()
    print(board.turn)
    board.undo_last_move()
    print(board.board[6][4], board.board[6][4].row, board.board[6][4].col, board.board[6][4].valid_moves)
    print(board.turn)
    board.print_board()
    print(board.move("first", (6, 4), (4, 4)))
    board.print_board()
    print(board.turn)
    board.undo_last_move()
    print(board.turn)
    board.print_board()
    board.move("first", (6, 4), (4, 4))
    board.print_board()
    board.move("second", (0, 1), (2, 2))
    board.print_board()
    board.move("first", (7, 6), (5, 5))
    board.print_board()
    board.undo_last_move()
    board.undo_last_move()
    board.undo_last_move()
    board.print_board()

f()